### ISSUE TITLE
Clarification on Readme

### ISSUE THREAD

**Issue by lamyergeier** [DividedGibon/Facebook_Messages_Bulk#1]
> Open [Facebook Messenger](https://www.facebook.com/messages/) in a desktop web browser with developer options enabled

Does it mean that we need to open the web developer tools of browser? But I am not sure as this is Step 3 in the Readme.md

I could not find such option on  [Facebook Messenger](https://www.facebook.com/messages/)

**Comment by DividedGibon** [comment]
> > Open [Facebook Messenger](https://www.facebook.com/messages/) in a desktop web browser with developer options enabled
> 
> 
> 
> Does it mean that we need to open the web developer tools of browser? But I am not sure as this is Step 3 in the Readme.md
> 
> 
> 
> I could not find such option on  [Facebook Messenger](https://www.facebook.com/messages/) 

Hi there :) 

Yes!  Great point - the wording isn't clear there.  So the first step means use a browser which has developer functionality available (I.e. a console window), such as Google chrome. Step 3 is how to access the developer tools. I'll tidy this up.
